spring.application.name=Consensus

# Alpha Vantage
alphavantage.api.key=G6Z5T1MTTV55KKQ2
alphavantage.base.url=https://www.alphavantage.co

# JPA / Postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
