spring.application.name=Consensus
spring.flyway.enabled=false

# Alpha Vantage
alphavantage.api.key={AV_API_KEY}
alphavantage.base.url={AV_BASE_URL}

# JPA / Postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=consensus-group

jwt.secret=${JWT_SECRET}